"""Who built this pull request — the one answer, used by the gate and by everything that routes.

WHY THIS IS ITS OWN MODULE. Independence was derived in three places and two of them disagreed. The
gate read the pull request's own commit list; the routing read a merge-base range in a local clone.
Those are different sets of commits, so a reviewer was told it was independent, posted a verdict, and
had to withdraw it when the gate refused. **A routing rule that does not match the gate sends roles
to do work that will not be accepted**, which is worse than sending them nowhere.

AN ARCHIVE COMMIT DOES NOT MAKE YOU AN AUTHOR, AND THE DIFF DECIDES THAT — NEVER THE SUBJECT LINE.

The product role must commit `openspec archive` onto the branch before merging, so product ends up an
author of every feature pull request, and after that only qa can certify one. Measured: eleven pull
requests, eight red for want of a verdict, exactly one role eligible to give it. A single point of
failure by construction, and it failed.

Independence exists so nobody certifies their own judgement about the product. An archive commit
carries no such judgement — generated by a command, touching nothing but `openspec/`, with a second
gate already refusing it if hand-authored. **So the exemption is earned by the diff: a commit is
spec-only when it changes no path outside `openspec/`.** A subject line is a claim; a diff is a fact.
Exempting `chore(...): archive ...` by its message would let any agent carry code through the one
gate in this process that is not mechanical, by naming a commit after a thing it is not.

AN EMPTY AUTHOR SET HAS TWO MEANINGS AND THEY ARE NOT THE SAME FACT — AND A THIRD IS NOT AN AUTHOR
SET AT ALL:

    no `Agent:` trailer anywhere    -> NoTrailers.   Who built this cannot be determined from the
                                      commits. A commit defect; the naming gate reports the remedy.
    trailers present, all spec-only -> Authors(set()) DETERMINED that nobody authored product
                                      judgement, so every role is independent.
    the lookup failed               -> LookupFailure raised. NOT an author set (Issue #79).

The bash version signalled the third with exit 3, and the first version of the exemption collapsed
all of them into one empty list: `--pr` printed nothing and exited 0 under a secondary rate limit,
the queue read that as "nobody built it, every role is independent", and offered a pull request
carrying nine `Agent: dev` trailers to dev. The gate re-derives from git at verdict time, where the
lookup does not fail, so it saw `dev` and refused the review dev had just done.

**In Python that collapse is not available.** `LookupFailure` is an exception; there is no way to
receive one and mistake it for a set.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass

from gh import Client, LookupFailure

AGENT_TRAILER = re.compile(r"^Agent:[ \t]*(\S+)[ \t]*$", re.MULTILINE)


class NoTrailers(Exception):
    """No commit carries an `Agent:` trailer, so authorship cannot be established from them.

    A DISTINCT OUTCOME FROM "NOBODY AUTHORED PRODUCT JUDGEMENT", and conflating the two is how an
    archive-only pull request became unmergeable while a trailerless one looked reviewable.
    """


@dataclass(frozen=True)
class Commit:
    sha: str
    message: str
    files: tuple[str, ...]

    @property
    def agent(self) -> str:
        m = AGENT_TRAILER.search(self.message.replace("\r", ""))
        return m.group(1) if m else ""

    @property
    def spec_only(self) -> bool:
        """Changes nothing outside `openspec/`.

        A COMMIT THAT CHANGED NO FILES IS NOT SPEC-ONLY. An empty file list is what an unreadable
        one looks like, and `all()` over an empty sequence is True — so a lookup failure would have
        become an exemption. Callers reach here only with a list they actually read.
        """
        return bool(self.files) and all(f.startswith("openspec/") for f in self.files)


def is_spec_only(files: list[str]) -> bool:
    return bool(files) and all(f.startswith("openspec/") for f in files)


def authors_of(commits: list[Commit]) -> set[str]:
    """The roles that authored product judgement here.

    Raises NoTrailers when no commit carries one at all — which is not the same as "nobody did".
    """
    if not any(c.agent for c in commits):
        raise NoTrailers("no commit carries an `Agent:` trailer")
    return {c.agent for c in commits if c.agent and not c.spec_only}


def all_trailers(commits: list[Commit]) -> set[str]:
    """Every trailer, exemption NOT applied — for telling 'no trailers at all' from 'all spec-only'."""
    return {c.agent for c in commits if c.agent}


# -- from the API: what the routing uses ---------------------------------------
def from_pr(client: Client, repo: str, number: int) -> list[Commit]:
    """Every commit of a pull request, with its file list. Raises LookupFailure, never returns [].

    THE FILE LIST COSTS ONE CALL PER COMMIT and that is not an oversight: the exemption is earned by
    the diff, and the diff is the only thing that cannot be forged by naming a commit after
    something it is not.
    """
    raw = client.paginate(f"repos/{repo}/pulls/{number}/commits")
    if not raw:
        # AN EMPTY COMMIT LIST FOR AN OPEN PULL REQUEST IS NOT AN ANSWER. GitHub does not create one,
        # so this is a truncated read or a pull request that no longer exists.
        raise LookupFailure(f"pull request #{number} reported no commits at all")
    out: list[Commit] = []
    for c in raw:
        sha = c.get("sha", "")
        detail = client.get(f"repos/{repo}/commits/{sha}")
        files = tuple(f.get("filename", "") for f in (detail.get("files") or []))
        out.append(Commit(sha=sha, message=(c.get("commit") or {}).get("message", ""), files=files))
    return out


# -- from this clone: what the gate uses ---------------------------------------
def from_range(base: str, head: str, cwd: str | None = None) -> list[Commit]:
    """Every commit in base..head, from git. No network, so no lookup failure of the API kind —
    but an unreachable ref is still a question that was not answered."""
    shas = _git(["rev-list", f"{base}..{head}"], cwd).split()
    out: list[Commit] = []
    for sha in shas:
        msg = _git(["log", "-1", "--format=%B", sha], cwd)
        files = tuple(f for f in _git(
            ["show", "--name-only", "--format=", sha], cwd).split("\n") if f)
        out.append(Commit(sha=sha, message=msg, files=files))
    return out


def _git(args: list[str], cwd: str | None = None) -> str:
    try:
        r = subprocess.run(["git", *args], capture_output=True, text=True, cwd=cwd, check=False)
    except (OSError, subprocess.SubprocessError) as e:
        raise LookupFailure(f"could not run git {' '.join(args)}: {e}") from e
    if r.returncode != 0:
        # AN UNREACHABLE BASE IS A FAILED LOOKUP, NOT AN EMPTY RANGE. `git rev-list bad..head` exits
        # non-zero; reading its empty stdout as "no commits" would certify a pull request whose
        # commits were never examined.
        raise LookupFailure(
            f"git {' '.join(args)} failed: {' '.join(r.stderr.split())[:200]}"
        )
    return r.stdout
